"""
Blockchain Utility — SecureVote
Connects to Ganache local node via Web3.py.
Zero gas cost — uses Ganache's pre-funded accounts.

Smart Contract: VotingContract.sol (compiled ABI embedded below)
Handles:
  - castVote(token, candidateId)          → records vote on-chain
  - hasVoted(token)                       → checks duplicate
  - getVoteCount(candidateId)             → tally
  - isElectionActive()                    → gate check
"""

import os
import json
import secrets
import hashlib
import logging
from functools import lru_cache
from flask import current_app

logger = logging.getLogger(__name__)


# ── Lazy Web3 import ──────────────────────────────────────────────────────────
def _get_web3():
    try:
        from web3 import Web3
        return Web3
    except ImportError:
        raise RuntimeError("web3 not installed. Run: pip install web3")


# ─────────────────────────────────────────────────────────────────────────────
#  Embedded ABI for VotingContract.sol
#  (compile from contracts/VotingContract.sol using Hardhat/Truffle)
# ─────────────────────────────────────────────────────────────────────────────

VOTING_ABI = [
    {"inputs": [{"name": "_candidateIds", "type": "bytes32[]"},
                {"name": "_candidateNames", "type": "string[]"}],
     "stateMutability": "nonpayable", "type": "constructor"},
    {"inputs": [{"name": "tokenHash", "type": "bytes32"},
                {"name": "candidateId", "type": "bytes32"}],
     "name": "castVote", "outputs": [],
     "stateMutability": "nonpayable", "type": "function"},
    {"inputs": [{"name": "tokenHash", "type": "bytes32"}],
     "name": "hasVoted", "outputs": [{"name": "", "type": "bool"}],
     "stateMutability": "view", "type": "function"},
    {"inputs": [{"name": "candidateId", "type": "bytes32"}],
     "name": "getVoteCount", "outputs": [{"name": "", "type": "uint256"}],
     "stateMutability": "view", "type": "function"},
    {"inputs": [],
     "name": "isActive", "outputs": [{"name": "", "type": "bool"}],
     "stateMutability": "view", "type": "function"},
    {"inputs": [],
     "name": "startElection", "outputs": [],
     "stateMutability": "nonpayable", "type": "function"},
    {"inputs": [],
     "name": "endElection", "outputs": [],
     "stateMutability": "nonpayable", "type": "function"},
    {"inputs": [],
     "name": "getTotalVotes", "outputs": [{"name": "", "type": "uint256"}],
     "stateMutability": "view", "type": "function"},
    {"anonymous": False,
     "inputs": [{"indexed": True, "name": "tokenHash", "type": "bytes32"},
                {"indexed": True, "name": "candidateId", "type": "bytes32"},
                {"indexed": False, "name": "timestamp", "type": "uint256"}],
     "name": "VoteCast", "type": "event"},
]


# ─────────────────────────────────────────────────────────────────────────────
#  CONNECTION
# ─────────────────────────────────────────────────────────────────────────────

def get_w3():
    """Return connected Web3 instance (Ganache)."""
    Web3 = _get_web3()
    uri = current_app.config.get("WEB3_PROVIDER_URI", "http://127.0.0.1:7545")
    w3 = Web3(Web3.HTTPProvider(uri))
    if not w3.is_connected():
        raise ConnectionError(f"Cannot connect to blockchain node at {uri}. "
                              "Start Ganache: ganache --port 7545")
    return w3


def get_deployer_account(w3):
    """Return Ganache's first pre-funded account as deployer."""
    return w3.eth.accounts[0]


# ─────────────────────────────────────────────────────────────────────────────
#  SMART CONTRACT DEPLOYMENT
# ─────────────────────────────────────────────────────────────────────────────

def deploy_voting_contract(candidate_ids: list[str],
                            candidate_names: list[str]) -> str:
    """
    Deploy VotingContract to Ganache with candidates.
    Returns deployed contract address.
    Free — Ganache mines for free.
    """
    Web3 = _get_web3()
    w3 = get_w3()
    deployer = get_deployer_account(w3)

    # Load compiled bytecode (generated by Hardhat/Truffle)
    bytecode = _load_bytecode()

    # Encode candidate IDs as bytes32
    ids_bytes32  = [Web3.to_bytes(text=cid).ljust(32, b'\x00')[:32] for cid in candidate_ids]

    Contract = w3.eth.contract(abi=VOTING_ABI, bytecode=bytecode)
    tx_hash = Contract.constructor(ids_bytes32, candidate_names).transact(
        {"from": deployer, "gas": 3_000_000}
    )
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
    logger.info(f"Contract deployed at: {receipt.contractAddress}")
    return receipt.contractAddress


def _load_bytecode() -> str:
    """Load compiled contract bytecode from artifacts directory."""
    artifact_path = os.path.join(
        os.path.dirname(__file__), "..", "..", "contracts",
        "artifacts", "VotingContract.json"
    )
    if os.path.exists(artifact_path):
        with open(artifact_path) as f:
            return json.load(f)["bytecode"]
    # Fallback: minimal bytecode for testing (deploy without full compile)
    logger.warning("Contract artifact not found — using stub bytecode.")
    return "0x"


# ─────────────────────────────────────────────────────────────────────────────
#  VOTING OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────

def cast_vote_on_chain(contract_address: str,
                        token: str,
                        candidate_id: str) -> dict:
    """
    Submit vote to blockchain smart contract.
    Token is hashed → anonymity preserved on ledger.

    Returns: {"success": bool, "tx_hash": str, "block_number": int}
    """
    Web3 = _get_web3()
    w3 = get_w3()
    deployer = get_deployer_account(w3)

    contract = w3.eth.contract(address=contract_address, abi=VOTING_ABI)

    # Hash token for on-chain anonymity
    token_hash = Web3.keccak(text=token)
    cand_bytes  = Web3.to_bytes(text=candidate_id).ljust(32, b'\x00')[:32]

    # Check duplicate BEFORE submitting
    if contract.functions.hasVoted(token_hash).call():
        return {"success": False, "error": "Smart contract: token already used"}

    # Send transaction — free on Ganache
    tx_hash = contract.functions.castVote(token_hash, cand_bytes).transact(
        {"from": deployer, "gas": 200_000}
    )
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

    return {
        "success":      True,
        "tx_hash":      receipt.transactionHash.hex(),
        "block_number": receipt.blockNumber,
        "gas_used":     receipt.gasUsed,
    }


def get_vote_counts(contract_address: str,
                    candidate_ids: list[str]) -> dict:
    """
    Read vote tallies from blockchain (view call — free).
    Returns: {candidate_id: vote_count}
    """
    Web3 = _get_web3()
    w3 = get_w3()
    contract = w3.eth.contract(address=contract_address, abi=VOTING_ABI)

    counts = {}
    for cid in candidate_ids:
        cand_bytes = Web3.to_bytes(text=cid).ljust(32, b'\x00')[:32]
        counts[cid] = contract.functions.getVoteCount(cand_bytes).call()
    return counts


def get_chain_info() -> dict:
    """Return basic blockchain stats."""
    w3 = get_w3()
    return {
        "connected":    True,
        "block_number": w3.eth.block_number,
        "chain_id":     w3.eth.chain_id,
        "accounts":     len(w3.eth.accounts),
        "node_uri":     current_app.config.get("WEB3_PROVIDER_URI"),
    }


def check_duplicate_vote(contract_address: str, token: str) -> bool:
    """Return True if token already used (duplicate)."""
    Web3 = _get_web3()
    w3 = get_w3()
    contract = w3.eth.contract(address=contract_address, abi=VOTING_ABI)
    token_hash = Web3.keccak(text=token)
    return contract.functions.hasVoted(token_hash).call()


# ─────────────────────────────────────────────────────────────────────────────
#  TOKEN UTILITIES
# ─────────────────────────────────────────────────────────────────────────────

def generate_anonymous_token(voter_uuid: str, election_id: str) -> str:
    """
    Generate one-time anonymous voting token.
    Uses HMAC so it's unpredictable but deterministic per voter+election.
    Once used, the smart contract nullifies it.
    """
    secret = current_app.config.get("JWT_SECRET", "jwt-secret")
    random_salt = secrets.token_hex(16)
    raw = f"{voter_uuid}:{election_id}:{random_salt}:{secret}"
    token_hash = hashlib.sha256(raw.encode()).hexdigest()
    return f"SVT-{token_hash[:40].upper()}"


def get_blockchain_explorer_url(tx_hash: str) -> str:
    """Returns Ganache explorer URL (local)."""
    return f"http://localhost:7545/tx/{tx_hash}"
